name: traffic-dumper-build

on:
    push:
        branches: ["**"]
        paths:
            - '.github/workflows/traffic-dumper-build.yml'
            - 'dockerfiles/Dockerfile.dpdk'
            - 'lumina/roce-pkt-dump/**'

    pull_request:
        branches: ["**"]
        paths:
            - '.github/workflows/traffic-dumper-build.yml'
            - 'dockerfiles/Dockerfile.dpdk'
            - 'lumina/roce-pkt-dump/**'

env:
    DOCKER_IMAGE_NAME: docker-ubuntu-with-dpdk

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Build Docker image with DPDK installed
              run: |
                    USER=$(id -un)
                    UID=$(id -u)
                    GUID=$(id -g)
                    docker build -t $DOCKER_IMAGE_NAME \
                    -f dockerfiles/Dockerfile.dpdk \
                    --build-arg USER="$USER" \
                    --build-arg UID="$UID" \
                    --build-arg GUID="$GUID" \
                    .

            - name: Start Docker container and build traffic dumper
              run: |
                    USER=$(id -un)
                    docker run --rm \
                    -v ./lumina/roce-pkt-dump:/home/$USER/roce-pkt-dump \
                    $DOCKER_IMAGE_NAME \
                    bash -c \
                    "cd /home/$USER/roce-pkt-dump; make clean; make"
