name: traffic-generator-build

on:
    push:
        branches: ["**"]
        paths:
            - '.github/workflows/traffic-generator-build.yml'
            - 'dockerfiles/Dockerfile.ofed'
            - 'lumina/my-ib-traffic-gen/**'

    pull_request:
        branches: ["**"]
        paths:
            - '.github/workflows/traffic-generator-build.yml'
            - 'dockerfiles/Dockerfile.ofed'
            - 'lumina/my-ib-traffic-gen/**'

env:
    DOCKER_IMAGE_NAME: docker-ubuntu-with-ofed

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Build Docker image with OFED installed
              run: |
                USER_NAME=$(id -un)
                USER_ID=$(id -u)
                GROUP_ID=$(id -g)
                docker build -t $DOCKER_IMAGE_NAME \
                    -f dockerfiles/Dockerfile.ofed \
                    --build-arg USER="$USER_NAME" \
                    --build-arg UID="$USER_ID" \
                    --build-arg GID="$GROUP_ID" \
                    .

            - name: Start Docker container and build RDMA traffic generator
              run: |
                docker run --rm \
                    -v ./lumina/my-ib-traffic-gen:/home/$USER_NAME/my-ib-traffic-gen \
                    $DOCKER_IMAGE_NAME \
                    bash -c \
                    "cd /home/$USER_NAME/my-ib-traffic-gen; make clean; make"
