name: traffic-dumper-build

on:
    push:
        branches: ["**"]
        paths:
            - '.github/workflows/traffic-dumper-build.yml'
            - 'dockerfiles/Dockerfile.dpdk'
            - 'lumina/roce-pkt-dump'

    pull_request:
        branches: ["**"]
        paths:
            - '.github/workflows/traffic-dumper-build.yml'
            - 'dockerfiles/Dockerfile.dpdk'
            - 'lumina/roce-pkt-dump'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Build Docker image with DPDK installed
              run: |
                    docker build -t docker-ubuntu-with-dpdk -f dockerfiles/Dockerfile.dpdk .

            - name: Build Traffic Dumper
              run: |
                    docker run --rm -v $PWD:/lumina/roce-pkt-dump -w /roce-pkt-dump docker-ubuntu-with-dpdk bash -c "cd /roce-pkt-dump && make"
