name: traffic-dumper-build

on:
    push:
        branches: ["**"]
        paths:
            - '.github/workflows/traffic-dumper-build.yml'
            - 'dockerfiles/Dockerfile.dpdk'
            - 'lumina/roce-pkt-dump/**'

    pull_request:
        branches: ["**"]
        paths:
            - '.github/workflows/traffic-dumper-build.yml'
            - 'dockerfiles/Dockerfile.dpdk'
            - 'lumina/roce-pkt-dump/**'

env:
    DOCKER_IMAGE_NAME: docker-ubuntu-with-dpdk
    UBUNTU_VERSION: 20.04

jobs:
    build:
        runs-on: ubuntu-$UBUNTU_VERSION
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Build Docker image with DPDK installed
              run: |
                USER_NAME=$(id -un)
                USER_ID=$(id -u)
                GROUP_ID=$(id -g)
                docker build -t $DOCKER_IMAGE_NAME \
                    -f dockerfiles/Dockerfile.dpdk \
                    --build-arg USER="$USER_NAME" \
                    --build-arg UID="$USER_ID" \
                    --build-arg GID="$GROUP_ID" \
                    --build-arg UBUNTU_VERSION="$UBUNTU_VERSION" \
                    .

            - name: Start Docker container and build traffic dumper
              run: |
                docker run --rm \
                    -v ./lumina/roce-pkt-dump:/home/$USER_NAME/roce-pkt-dump \
                    $DOCKER_IMAGE_NAME \
                    bash -c \
                    "cd /home/$USER_NAME/roce-pkt-dump; make clean; make"
