name: traffic-dumper-build

on:
    push:
        branches: ["**"]
        paths:
            - '.github/workflows/traffic-dumper-build.yml'
            - 'dockerfiles/Dockerfile.dpdk'
            - 'lumina/roce-pkt-dump/**'

    pull_request:
        branches: ["**"]
        paths:
            - '.github/workflows/traffic-dumper-build.yml'
            - 'dockerfiles/Dockerfile.dpdk'
            - 'lumina/roce-pkt-dump/**'

env:
    DOCKER_USERNAME: "lumina-user"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Build Docker image with DPDK installed
              run: |
                    docker build -t docker-ubuntu-with-dpdk \
                    -f dockerfiles/Dockerfile.dpdk \
                    --build-arg="USERNAME=$DOCKER_USERNAME" \
                    .

            - name: Start Docker container and build traffic dumper
              run: |
                    docker run --rm \
                    -v ./lumina/roce-pkt-dump:/home/$DOCKER_USERNAME/roce-pkt-dump \
                    docker-ubuntu-with-dpdk \
                    bash -c \
                    "sudo chown -R $DOCKER_USERNAME /home/$DOCKER_USERNAME/roce-pkt-dump/ && \
                    cd /home/$DOCKER_USERNAME/roce-pkt-dump && \
                    sudo make"
